owner: h3infra
repo: orderart-monitor

sites:

  
  - name: Orderart
    url: https://www.orderart.com.au/
  - name: Amrapali Indian Cuisine
    url: https://www.amrapali.com.au/
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  baseUrl: /orderart-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Orderart website status
  
  navbar:
    - title: Status
      href: /

