owner: h3infra
repo: orderart-monitor

sites:
  - name: Orderart
    url: https://www.orderart.com.au/
  - name: Amrapali Indian Cuisine
    url: https://www.amrapali.com.au/
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  baseUrl: /
  cname: null
  name: Orderart Status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: "**Orderart Status Page**"
  introMessage: Monitoring uptime of [Orderart](https://www.orderart.com.au) in real time.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/h3infra/orderart-monitor
