name: Notify on Incident Open

on:
  issues:
    types:
      - opened

jobs:
  notify:
    if: contains(join(github.event.issue.labels.*.name, ','), 'incident')
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook
        run: |
          curl -X POST http://3.105.188.182:5678/webhook/upptime-alert \
          -H "Content-Type: application/json" \
          -d '{"site": "${{ github.event.issue.title }}"}'
